// =============================================
// CODAPOS — 10 Storefront Template Themes
// =============================================

export interface StoreTheme {
    id: string;
    name: string;
    preview: string;        // emoji preview
    style: "shopee" | "gofood";
    // Background
    bgBase: string;         // main bg color
    bgGradient: string;     // gradient overlay class
    bgGlow1: string;        // glow blob 1 color
    bgGlow2: string;        // glow blob 2 color
    // Accent
    accent: string;         // primary accent hex
    accentLight: string;    // lighter variant
    accentGradient: string; // gradient CSS for buttons/tags
    // Text
    textPrimary: string;
    textSecondary: string;
    textMuted: string;
    // Cards
    cardBg: string;
    cardBorder: string;
    cardHoverBorder: string;
    cardHoverBg: string;
    // Search input
    searchBg: string;
    searchBorder: string;
    searchFocus: string;
    searchPlaceholder: string;
    // Category chip
    chipActiveBg: string;
    chipActiveText: string;
    chipBg: string;
    chipText: string;
    chipBorder: string;
    // Footer
    footerBg: string;
    footerBorder: string;
    footerText: string;
    // Badge
    badgeBg: string;
    badgeText: string;
    // Price text
    priceColor: string;
    // Extra CSS classes
    bodyClass: string;
}

// ==================== 5 SHOPEE-STYLE (DARK) ====================

const darkBase = {
    style: "shopee" as const,
    bgBase: "#0a0a0f",
    textPrimary: "text-white",
    textSecondary: "text-white/60",
    textMuted: "text-white/30",
    searchBg: "bg-white/5",
    searchBorder: "border-white/10",
    searchPlaceholder: "placeholder:text-white/25",
    chipBg: "bg-white/5",
    chipText: "text-white/50",
    chipBorder: "border border-white/10",
    badgeBg: "bg-black/50",
    badgeText: "text-white/70",
    bodyClass: "storefront-dark",
};

// ==================== 5 GOFOOD-STYLE (WHITE) ====================

const lightBase = {
    style: "gofood" as const,
    bgBase: "#FAFBFC",
    textPrimary: "text-gray-900",
    textSecondary: "text-gray-600",
    textMuted: "text-gray-400",
    searchBg: "bg-white",
    searchBorder: "border-gray-200",
    searchPlaceholder: "placeholder:text-gray-300",
    chipBg: "bg-gray-100",
    chipText: "text-gray-500",
    chipBorder: "border border-gray-200",
    badgeBg: "bg-white/90",
    badgeText: "text-gray-600",
    bodyClass: "storefront-light",
};

export const STORE_THEMES: StoreTheme[] = [
    // ===== 1. Shopee Dark Blue (DEFAULT) =====
    {
        ...darkBase,
        id: "shopee-dark-blue",
        name: "Dark Blue",
        preview: "🌊",
        accent: "#1DA1F2",
        accentLight: "#A7D8FF",
        accentGradient: "linear-gradient(135deg, #1DA1F2, #4DB5F5)",
        bgGradient: "from-[#1DA1F2]/10 to-transparent",
        bgGlow1: "#1DA1F2",
        bgGlow2: "#A7D8FF",
        cardBg: "bg-white/[0.04]",
        cardBorder: "border-white/[0.08]",
        cardHoverBorder: "hover:border-white/20",
        cardHoverBg: "hover:bg-white/[0.07]",
        searchFocus: "focus:border-[#1DA1F2]/50 focus:ring-[#1DA1F2]/10",
        chipActiveBg: "bg-gradient-to-r from-[#1DA1F2] to-[#4DB5F5]",
        chipActiveText: "text-white",
        footerBg: "bg-[#0a0a0f]/90",
        footerBorder: "border-white/5",
        footerText: "text-white/25",
        priceColor: "text-[#1DA1F2]",
    },
    // ===== 2. Shopee Dark Orange =====
    {
        ...darkBase,
        id: "shopee-dark-orange",
        name: "Dark Orange",
        preview: "🔥",
        accent: "#EE4D2D",
        accentLight: "#FFB49A",
        accentGradient: "linear-gradient(135deg, #EE4D2D, #FF6742)",
        bgGradient: "from-[#EE4D2D]/10 to-transparent",
        bgGlow1: "#EE4D2D",
        bgGlow2: "#FFB49A",
        cardBg: "bg-white/[0.04]",
        cardBorder: "border-white/[0.08]",
        cardHoverBorder: "hover:border-[#EE4D2D]/30",
        cardHoverBg: "hover:bg-white/[0.07]",
        searchFocus: "focus:border-[#EE4D2D]/50 focus:ring-[#EE4D2D]/10",
        chipActiveBg: "bg-gradient-to-r from-[#EE4D2D] to-[#FF6742]",
        chipActiveText: "text-white",
        footerBg: "bg-[#0a0a0f]/90",
        footerBorder: "border-white/5",
        footerText: "text-white/25",
        priceColor: "text-[#EE4D2D]",
    },
    // ===== 3. Shopee Dark Purple =====
    {
        ...darkBase,
        id: "shopee-dark-purple",
        name: "Dark Purple",
        preview: "💜",
        accent: "#8B5CF6",
        accentLight: "#C4B5FD",
        accentGradient: "linear-gradient(135deg, #8B5CF6, #A78BFA)",
        bgGradient: "from-[#8B5CF6]/10 to-transparent",
        bgGlow1: "#8B5CF6",
        bgGlow2: "#C4B5FD",
        cardBg: "bg-white/[0.04]",
        cardBorder: "border-white/[0.08]",
        cardHoverBorder: "hover:border-[#8B5CF6]/30",
        cardHoverBg: "hover:bg-white/[0.07]",
        searchFocus: "focus:border-[#8B5CF6]/50 focus:ring-[#8B5CF6]/10",
        chipActiveBg: "bg-gradient-to-r from-[#8B5CF6] to-[#A78BFA]",
        chipActiveText: "text-white",
        footerBg: "bg-[#0a0a0f]/90",
        footerBorder: "border-white/5",
        footerText: "text-white/25",
        priceColor: "text-[#8B5CF6]",
    },
    // ===== 4. Shopee Dark Pink =====
    {
        ...darkBase,
        id: "shopee-dark-pink",
        name: "Dark Pink",
        preview: "💗",
        accent: "#EC4899",
        accentLight: "#F9A8D4",
        accentGradient: "linear-gradient(135deg, #EC4899, #F472B6)",
        bgGradient: "from-[#EC4899]/10 to-transparent",
        bgGlow1: "#EC4899",
        bgGlow2: "#F9A8D4",
        cardBg: "bg-white/[0.04]",
        cardBorder: "border-white/[0.08]",
        cardHoverBorder: "hover:border-[#EC4899]/30",
        cardHoverBg: "hover:bg-white/[0.07]",
        searchFocus: "focus:border-[#EC4899]/50 focus:ring-[#EC4899]/10",
        chipActiveBg: "bg-gradient-to-r from-[#EC4899] to-[#F472B6]",
        chipActiveText: "text-white",
        footerBg: "bg-[#0a0a0f]/90",
        footerBorder: "border-white/5",
        footerText: "text-white/25",
        priceColor: "text-[#EC4899]",
    },
    // ===== 5. Shopee Dark Cyan =====
    {
        ...darkBase,
        id: "shopee-dark-cyan",
        name: "Dark Cyan",
        preview: "🧊",
        accent: "#06B6D4",
        accentLight: "#A5F3FC",
        accentGradient: "linear-gradient(135deg, #06B6D4, #22D3EE)",
        bgGradient: "from-[#06B6D4]/10 to-transparent",
        bgGlow1: "#06B6D4",
        bgGlow2: "#A5F3FC",
        cardBg: "bg-white/[0.04]",
        cardBorder: "border-white/[0.08]",
        cardHoverBorder: "hover:border-[#06B6D4]/30",
        cardHoverBg: "hover:bg-white/[0.07]",
        searchFocus: "focus:border-[#06B6D4]/50 focus:ring-[#06B6D4]/10",
        chipActiveBg: "bg-gradient-to-r from-[#06B6D4] to-[#22D3EE]",
        chipActiveText: "text-white",
        footerBg: "bg-[#0a0a0f]/90",
        footerBorder: "border-white/5",
        footerText: "text-white/25",
        priceColor: "text-[#06B6D4]",
    },

    // ===== 6. GoFood Green =====
    {
        ...lightBase,
        id: "gofood-green",
        name: "GoFood Green",
        preview: "🍀",
        accent: "#00AA5B",
        accentLight: "#86EFAC",
        accentGradient: "linear-gradient(135deg, #00AA5B, #22C55E)",
        bgGradient: "from-[#00AA5B]/5 to-transparent",
        bgGlow1: "#00AA5B",
        bgGlow2: "#86EFAC",
        cardBg: "bg-white",
        cardBorder: "border-gray-100",
        cardHoverBorder: "hover:border-[#00AA5B]/30",
        cardHoverBg: "hover:shadow-lg hover:shadow-green-500/5",
        searchFocus: "focus:border-[#00AA5B]/50 focus:ring-[#00AA5B]/10",
        chipActiveBg: "bg-gradient-to-r from-[#00AA5B] to-[#22C55E]",
        chipActiveText: "text-white",
        footerBg: "bg-white/95",
        footerBorder: "border-gray-100",
        footerText: "text-gray-400",
        priceColor: "text-[#00AA5B]",
    },
    // ===== 7. GoFood Blue =====
    {
        ...lightBase,
        id: "gofood-blue",
        name: "GoFood Blue",
        preview: "💎",
        accent: "#2563EB",
        accentLight: "#93C5FD",
        accentGradient: "linear-gradient(135deg, #2563EB, #3B82F6)",
        bgGradient: "from-[#2563EB]/5 to-transparent",
        bgGlow1: "#2563EB",
        bgGlow2: "#93C5FD",
        cardBg: "bg-white",
        cardBorder: "border-gray-100",
        cardHoverBorder: "hover:border-[#2563EB]/30",
        cardHoverBg: "hover:shadow-lg hover:shadow-blue-500/5",
        searchFocus: "focus:border-[#2563EB]/50 focus:ring-[#2563EB]/10",
        chipActiveBg: "bg-gradient-to-r from-[#2563EB] to-[#3B82F6]",
        chipActiveText: "text-white",
        footerBg: "bg-white/95",
        footerBorder: "border-gray-100",
        footerText: "text-gray-400",
        priceColor: "text-[#2563EB]",
    },
    // ===== 8. GoFood Red =====
    {
        ...lightBase,
        id: "gofood-red",
        name: "GoFood Red",
        preview: "🌹",
        accent: "#DC2626",
        accentLight: "#FCA5A5",
        accentGradient: "linear-gradient(135deg, #DC2626, #EF4444)",
        bgGradient: "from-[#DC2626]/5 to-transparent",
        bgGlow1: "#DC2626",
        bgGlow2: "#FCA5A5",
        cardBg: "bg-white",
        cardBorder: "border-gray-100",
        cardHoverBorder: "hover:border-[#DC2626]/30",
        cardHoverBg: "hover:shadow-lg hover:shadow-red-500/5",
        searchFocus: "focus:border-[#DC2626]/50 focus:ring-[#DC2626]/10",
        chipActiveBg: "bg-gradient-to-r from-[#DC2626] to-[#EF4444]",
        chipActiveText: "text-white",
        footerBg: "bg-white/95",
        footerBorder: "border-gray-100",
        footerText: "text-gray-400",
        priceColor: "text-[#DC2626]",
    },
    // ===== 9. GoFood Glass (Glassmorphism) =====
    {
        ...lightBase,
        id: "gofood-glass",
        name: "GoFood Glass",
        preview: "✨",
        accent: "#6366F1",
        accentLight: "#C7D2FE",
        accentGradient: "linear-gradient(135deg, #6366F1, #818CF8)",
        bgBase: "#F0F2F5",
        bgGradient: "from-[#6366F1]/5 to-[#EC4899]/5",
        bgGlow1: "#6366F1",
        bgGlow2: "#EC4899",
        cardBg: "bg-white/60 backdrop-blur-xl",
        cardBorder: "border-white/50",
        cardHoverBorder: "hover:border-white/80",
        cardHoverBg: "hover:bg-white/80 hover:shadow-xl hover:shadow-indigo-500/5",
        searchBg: "bg-white/50 backdrop-blur-md",
        searchBorder: "border-white/40",
        searchFocus: "focus:border-[#6366F1]/50 focus:ring-[#6366F1]/10",
        chipActiveBg: "bg-gradient-to-r from-[#6366F1] to-[#818CF8]",
        chipActiveText: "text-white",
        chipBg: "bg-white/40 backdrop-blur-sm",
        footerBg: "bg-white/60 backdrop-blur-xl",
        footerBorder: "border-white/30",
        footerText: "text-gray-400",
        priceColor: "text-[#6366F1]",
        bodyClass: "storefront-light storefront-glass",
    },
    // ===== 10. GoFood Gold =====
    {
        ...lightBase,
        id: "gofood-gold",
        name: "GoFood Gold",
        preview: "👑",
        accent: "#D4A017",
        accentLight: "#FDE68A",
        accentGradient: "linear-gradient(135deg, #D4A017, #F59E0B)",
        bgBase: "#FFFDF7",
        bgGradient: "from-[#D4A017]/5 to-transparent",
        bgGlow1: "#D4A017",
        bgGlow2: "#FDE68A",
        cardBg: "bg-white",
        cardBorder: "border-amber-100",
        cardHoverBorder: "hover:border-[#D4A017]/40",
        cardHoverBg: "hover:shadow-lg hover:shadow-amber-500/10",
        searchFocus: "focus:border-[#D4A017]/50 focus:ring-[#D4A017]/10",
        chipActiveBg: "bg-gradient-to-r from-[#D4A017] to-[#F59E0B]",
        chipActiveText: "text-white",
        chipBorder: "border border-amber-200",
        chipBg: "bg-amber-50",
        chipText: "text-amber-700/60",
        footerBg: "bg-white/95",
        footerBorder: "border-amber-100",
        footerText: "text-amber-800/30",
        priceColor: "text-[#D4A017]",
        bodyClass: "storefront-light storefront-gold",
    },

    // ==================== 10 NEW MARKETPLACE THEMES ====================

    // ===== 11. Midnight Emerald (Tokopedia Dark) =====
    {
        ...darkBase,
        id: "dark-emerald",
        name: "Midnight Emerald",
        preview: "🌲",
        accent: "#00B48A",
        accentLight: "#6EE7B7",
        accentGradient: "linear-gradient(135deg, #00B48A, #34D399)",
        bgBase: "#080F0C",
        bgGradient: "from-[#00B48A]/10 to-transparent",
        bgGlow1: "#00B48A",
        bgGlow2: "#6EE7B7",
        cardBg: "bg-white/[0.04]",
        cardBorder: "border-white/[0.08]",
        cardHoverBorder: "hover:border-[#00B48A]/30",
        cardHoverBg: "hover:bg-white/[0.07]",
        searchFocus: "focus:border-[#00B48A]/50 focus:ring-[#00B48A]/10",
        chipActiveBg: "bg-gradient-to-r from-[#00B48A] to-[#34D399]",
        chipActiveText: "text-white",
        footerBg: "bg-[#080F0C]/90",
        footerBorder: "border-white/5",
        footerText: "text-white/25",
        priceColor: "text-[#00B48A]",
    },
    // ===== 12. Dark Rose (Blibli Dark) =====
    {
        ...darkBase,
        id: "dark-rose",
        name: "Dark Rose",
        preview: "🌺",
        accent: "#F43F5E",
        accentLight: "#FDA4AF",
        accentGradient: "linear-gradient(135deg, #F43F5E, #FB7185)",
        bgBase: "#0F0A0B",
        bgGradient: "from-[#F43F5E]/10 to-transparent",
        bgGlow1: "#F43F5E",
        bgGlow2: "#FDA4AF",
        cardBg: "bg-white/[0.04]",
        cardBorder: "border-white/[0.08]",
        cardHoverBorder: "hover:border-[#F43F5E]/30",
        cardHoverBg: "hover:bg-white/[0.07]",
        searchFocus: "focus:border-[#F43F5E]/50 focus:ring-[#F43F5E]/10",
        chipActiveBg: "bg-gradient-to-r from-[#F43F5E] to-[#FB7185]",
        chipActiveText: "text-white",
        footerBg: "bg-[#0F0A0B]/90",
        footerBorder: "border-white/5",
        footerText: "text-white/25",
        priceColor: "text-[#F43F5E]",
    },
    // ===== 13. Neon Violet (Bukalapak Dark) =====
    {
        ...darkBase,
        id: "dark-neon-violet",
        name: "Neon Violet",
        preview: "⚡",
        accent: "#7C3AED",
        accentLight: "#C4B5FD",
        accentGradient: "linear-gradient(135deg, #7C3AED, #A78BFA)",
        bgBase: "#0B0A10",
        bgGradient: "from-[#7C3AED]/10 to-[#EC4899]/5",
        bgGlow1: "#7C3AED",
        bgGlow2: "#EC4899",
        cardBg: "bg-white/[0.04]",
        cardBorder: "border-white/[0.08]",
        cardHoverBorder: "hover:border-[#7C3AED]/30",
        cardHoverBg: "hover:bg-white/[0.07]",
        searchFocus: "focus:border-[#7C3AED]/50 focus:ring-[#7C3AED]/10",
        chipActiveBg: "bg-gradient-to-r from-[#7C3AED] to-[#A78BFA]",
        chipActiveText: "text-white",
        footerBg: "bg-[#0B0A10]/90",
        footerBorder: "border-white/5",
        footerText: "text-white/25",
        priceColor: "text-[#7C3AED]",
    },
    // ===== 14. Dark Amber (Lazada Dark) =====
    {
        ...darkBase,
        id: "dark-amber",
        name: "Dark Amber",
        preview: "🔶",
        accent: "#F59E0B",
        accentLight: "#FDE68A",
        accentGradient: "linear-gradient(135deg, #F59E0B, #FBBF24)",
        bgBase: "#0F0D08",
        bgGradient: "from-[#F59E0B]/10 to-transparent",
        bgGlow1: "#F59E0B",
        bgGlow2: "#FDE68A",
        cardBg: "bg-white/[0.04]",
        cardBorder: "border-white/[0.08]",
        cardHoverBorder: "hover:border-[#F59E0B]/30",
        cardHoverBg: "hover:bg-white/[0.07]",
        searchFocus: "focus:border-[#F59E0B]/50 focus:ring-[#F59E0B]/10",
        chipActiveBg: "bg-gradient-to-r from-[#F59E0B] to-[#FBBF24]",
        chipActiveText: "text-white",
        footerBg: "bg-[#0F0D08]/90",
        footerBorder: "border-white/5",
        footerText: "text-white/25",
        priceColor: "text-[#F59E0B]",
    },
    // ===== 15. Cosmic Teal (JD.ID Dark) =====
    {
        ...darkBase,
        id: "dark-cosmic-teal",
        name: "Cosmic Teal",
        preview: "🌌",
        accent: "#14B8A6",
        accentLight: "#99F6E4",
        accentGradient: "linear-gradient(135deg, #14B8A6, #2DD4BF)",
        bgBase: "#070D0D",
        bgGradient: "from-[#14B8A6]/10 to-[#0EA5E9]/5",
        bgGlow1: "#14B8A6",
        bgGlow2: "#0EA5E9",
        cardBg: "bg-white/[0.04]",
        cardBorder: "border-white/[0.08]",
        cardHoverBorder: "hover:border-[#14B8A6]/30",
        cardHoverBg: "hover:bg-white/[0.07]",
        searchFocus: "focus:border-[#14B8A6]/50 focus:ring-[#14B8A6]/10",
        chipActiveBg: "bg-gradient-to-r from-[#14B8A6] to-[#2DD4BF]",
        chipActiveText: "text-white",
        footerBg: "bg-[#070D0D]/90",
        footerBorder: "border-white/5",
        footerText: "text-white/25",
        priceColor: "text-[#14B8A6]",
    },

    // ===== 16. Tokopedia Green =====
    {
        ...lightBase,
        id: "tokopedia-green",
        name: "Tokopedia Green",
        preview: "🟢",
        accent: "#42B549",
        accentLight: "#86EFAC",
        accentGradient: "linear-gradient(135deg, #42B549, #66CC6E)",
        bgBase: "#F7FBF7",
        bgGradient: "from-[#42B549]/5 to-transparent",
        bgGlow1: "#42B549",
        bgGlow2: "#86EFAC",
        cardBg: "bg-white",
        cardBorder: "border-gray-100",
        cardHoverBorder: "hover:border-[#42B549]/30",
        cardHoverBg: "hover:shadow-lg hover:shadow-green-500/8",
        searchFocus: "focus:border-[#42B549]/50 focus:ring-[#42B549]/10",
        chipActiveBg: "bg-gradient-to-r from-[#42B549] to-[#66CC6E]",
        chipActiveText: "text-white",
        footerBg: "bg-white/95",
        footerBorder: "border-gray-100",
        footerText: "text-gray-400",
        priceColor: "text-[#42B549]",
    },
    // ===== 17. Blibli Blue =====
    {
        ...lightBase,
        id: "blibli-blue",
        name: "Blibli Blue",
        preview: "🔵",
        accent: "#0072B9",
        accentLight: "#7DD3FC",
        accentGradient: "linear-gradient(135deg, #0072B9, #0EA5E9)",
        bgBase: "#F5F9FC",
        bgGradient: "from-[#0072B9]/5 to-transparent",
        bgGlow1: "#0072B9",
        bgGlow2: "#7DD3FC",
        cardBg: "bg-white",
        cardBorder: "border-blue-50",
        cardHoverBorder: "hover:border-[#0072B9]/30",
        cardHoverBg: "hover:shadow-lg hover:shadow-blue-500/8",
        searchFocus: "focus:border-[#0072B9]/50 focus:ring-[#0072B9]/10",
        chipActiveBg: "bg-gradient-to-r from-[#0072B9] to-[#0EA5E9]",
        chipActiveText: "text-white",
        footerBg: "bg-white/95",
        footerBorder: "border-blue-50",
        footerText: "text-gray-400",
        priceColor: "text-[#0072B9]",
    },
    // ===== 18. Lazada Orange =====
    {
        ...lightBase,
        id: "lazada-orange",
        name: "Lazada Orange",
        preview: "🍊",
        accent: "#F57224",
        accentLight: "#FDBA74",
        accentGradient: "linear-gradient(135deg, #F57224, #FB923C)",
        bgBase: "#FFFAF5",
        bgGradient: "from-[#F57224]/5 to-transparent",
        bgGlow1: "#F57224",
        bgGlow2: "#FDBA74",
        cardBg: "bg-white",
        cardBorder: "border-orange-50",
        cardHoverBorder: "hover:border-[#F57224]/30",
        cardHoverBg: "hover:shadow-lg hover:shadow-orange-500/8",
        searchFocus: "focus:border-[#F57224]/50 focus:ring-[#F57224]/10",
        chipActiveBg: "bg-gradient-to-r from-[#F57224] to-[#FB923C]",
        chipActiveText: "text-white",
        footerBg: "bg-white/95",
        footerBorder: "border-orange-50",
        footerText: "text-gray-400",
        priceColor: "text-[#F57224]",
    },
    // ===== 19. Bukalapak Pink =====
    {
        ...lightBase,
        id: "bukalapak-pink",
        name: "Bukalapak Pink",
        preview: "🩷",
        accent: "#E31C79",
        accentLight: "#F9A8D4",
        accentGradient: "linear-gradient(135deg, #E31C79, #F472B6)",
        bgBase: "#FDF5F9",
        bgGradient: "from-[#E31C79]/5 to-transparent",
        bgGlow1: "#E31C79",
        bgGlow2: "#F9A8D4",
        cardBg: "bg-white",
        cardBorder: "border-pink-50",
        cardHoverBorder: "hover:border-[#E31C79]/30",
        cardHoverBg: "hover:shadow-lg hover:shadow-pink-500/8",
        searchFocus: "focus:border-[#E31C79]/50 focus:ring-[#E31C79]/10",
        chipActiveBg: "bg-gradient-to-r from-[#E31C79] to-[#F472B6]",
        chipActiveText: "text-white",
        footerBg: "bg-white/95",
        footerBorder: "border-pink-50",
        footerText: "text-gray-400",
        priceColor: "text-[#E31C79]",
    },
    // ===== 20. Minimal White =====
    {
        ...lightBase,
        id: "minimal-white",
        name: "Minimal White",
        preview: "⬜",
        accent: "#111827",
        accentLight: "#9CA3AF",
        accentGradient: "linear-gradient(135deg, #111827, #374151)",
        bgBase: "#FFFFFF",
        bgGradient: "from-gray-100/50 to-transparent",
        bgGlow1: "#6B7280",
        bgGlow2: "#D1D5DB",
        cardBg: "bg-white",
        cardBorder: "border-gray-100",
        cardHoverBorder: "hover:border-gray-300",
        cardHoverBg: "hover:shadow-lg hover:shadow-gray-200/50",
        searchFocus: "focus:border-gray-400 focus:ring-gray-200/20",
        chipActiveBg: "bg-gradient-to-r from-gray-800 to-gray-700",
        chipActiveText: "text-white",
        chipBg: "bg-gray-50",
        chipText: "text-gray-500",
        chipBorder: "border border-gray-200",
        footerBg: "bg-gray-50",
        footerBorder: "border-gray-100",
        footerText: "text-gray-400",
        priceColor: "text-gray-900",
        bodyClass: "storefront-light storefront-minimal",
    },
];

export const DEFAULT_THEME_ID = "shopee-dark-blue";

export function getThemeById(id: string): StoreTheme {
    return STORE_THEMES.find((t) => t.id === id) || STORE_THEMES[0];
}
